INSERT INTO Project (name, description, created) VALUES ('dev project #1', 'a fake project created in dev environment', '550103178604182165');
INSERT INTO Project (name, description, created) VALUES ('dev project #2', 'a fake project created in dev environment', '550103178604182165');
INSERT INTO Project (name, description, created) VALUES ('dev project #3', 'a fake project created in dev environment', '550103178604182165');

INSERT INTO Procedure (name, description, created, pid) VALUES ('procedure #1-1', 'a fake procedure in dev', '550103178604182165', 1);
INSERT INTO Procedure (name, description, created, pid) VALUES ('procedure #1-2', 'a fake procedure in dev', '550103178604182165', 1);
INSERT INTO Procedure (name, description, created, pid) VALUES ('procedure #1-3', 'a fake procedure in dev', '550103178604182165', 1);
INSERT INTO Procedure (name, description, created, pid) VALUES ('procedure #2-1', 'a fake procedure in dev', '550103178604182165', 2);
INSERT INTO Procedure (name, description, created, pid) VALUES ('procedure #2-2', 'a fake procedure in dev', '550103178604182165', 2);

INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 1);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 1);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 1);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 1);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 1);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 2);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 2);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 2);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 2);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 2);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 2);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 2);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 3);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 3);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 3);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 4);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 4);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 4);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 4);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 4);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 4);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 4);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 5);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 5);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 5);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 5);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 5);
INSERT INTO Step (content, cid) VALUES ('{"content": "Do some action"}', 5);